resolver: lts-13.26
packages:
- '.'
extra-deps:
- bytestring-trie-0.2.5.0
- connection-0.3.1
- happy-1.19.9
- language-javascript-0.6.0.13
- network-3.0.1.1
- purescript-0.13.3
- socks-0.6.0
flags:
  aeson-pretty:
    lib-only: true
