resolver: lts-12.0
flags:
  pursuit:
    dev: true
packages:
- .
extra-deps:
- github: purescript/purescript
  commit: 1dc385e0d2fdf25e3fd445ab3d2c60442ac958de
- github: hdgarrood/bytestring-trie
  commit: 1ad63cfcfc59ff65d331e3be7029025765c3ca6f
